### Welcome to the Movie API

GET http://localhost:3000/

### Auth Endpoints
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "username": "johndoe",
    "email": "john.doe@example.com",
    "password": "password123",
    "phone": "1234567890",
    "birthday": "1990-01-01"
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"
}




### User Endpoints
GET http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ0OTBlNmNlOWZhMjYzZjc5MGY5NSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIwMzIsImV4cCI6MTc1NDA5NTYzMn0.U0sgw8BmOxkt-Brx_VYTSwK_7SAvjwf1NT-bXw1de7M


###     Update User
PUT http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ1MjQ5YjUxZGRhNzkzZTUzMDVjOSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIxMDcsImV4cCI6MTc1NDA5NTcwN30.mlgPk3P-ximu7UGMPcJRFrXnGNoGCZ69ZMInVChSmXs

{
    "firstname": "Paul",
    "lastname": "O'Connor",
    "username": "pauloconnor",
    "email": "paul.oconnor@example.com",
    "password": "password123",
    "phone": "1234567890",
    "birthday": "1990-01-01"
}

### Delete User
DELETE http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ1MjQ5YjUxZGRhNzkzZTUzMDVjOSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIxMDcsImV4cCI6MTc1NDA5NTcwN30.mlgPk3P-ximu7UGMPcJRFrXnGNoGCZ69ZMInVChSmXs

### Movie Endpoints
GET http://localhost:3000/api/movies/
Content-Type: application/application/json

### Movie Details
GET http://localhost:3000/api/movies/688d327b201c6ce93804f255
Content-Type: application/json

### Add Movie
POST http://localhost:3000/api/movies/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ1MjQ5YjUxZGRhNzkzZTUzMDVjOSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIxMDcsImV4cCI6MTc1NDA5NTcwN30.mlgPk3P-ximu7UGMPcJRFrXnGNoGCZ69ZMInVChSmXs


{
    "title": "Movie Title",
    "director": "Movie Director",
    "genre": "Movie Genre",
    "rating": 5,
    "duration": 120,
    "poster": "https://example.com/poster.jpg",
    "country": "Movie Country",
    "producer": "Movie Producer",
    "description": "Movie Description",
    "releaseDate": "2022-01-01"
}

### Update Movie
PUT http://localhost:3000/api/movies/688d327b201c6ce93804f255
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ1MjQ5YjUxZGRhNzkzZTUzMDVjOSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIxMDcsImV4cCI6MTc1NDA5NTcwN30.mlgPk3P-ximu7UGMPcJRFrXnGNoGCZ69ZMInVChSmXs

{
    "title": "Updated Movie Title",
    "director": "Updated Movie Director",
    "genre": "Updated Movie Genre",
    "rating": 5,
    "duration": 120,
    "poster": "Updated Movie Poster",
    "country": "Updated Movie Country",
    "producer": "Updated Movie Producer",
    "description": "Updated Movie Description",
    "releaseDate": "2022-01-01"
}

### Delete Movie
DELETE http://localhost:3000/api/movies/688d44bdd64f9a7545e4e339
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGQ0OTBlNmNlOWZhMjYzZjc5MGY5NSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTQwOTIwMzIsImV4cCI6MTc1NDA5NTYzMn0.U0sgw8BmOxkt-Brx_VYTSwK_7SAvjwf1NT-bXw1de7M
